config/routes.rb
Rails.application.routes.draw do
  namespace :admins_backoffice do
    get 'members/index'
    
  end
  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index' # Dashboard
    resources :admins # Administradores
    resources :members # Cadastro de Membros
    resources :archives #arquivos
    root to: 'archives#index'
  end
  devise_for :users
  devise_for :admins
 
  get 'inicio', to: 'site/welcome#index'
  get 'admin', to: 'admins_backoffice/welcome#index'
  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/archive.rb
class Archive < ApplicationRecord
    has_one_attached :file

     # kaminari
  paginates_per 5  
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:edit, :update, :destroy]
  

  def index
    @admins = Admin.all.page(params[:page])
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: 'Administrador cadastrado com sucesso'
    else 
      render :edit
    end
  end

  def edit
    #@admin = Admin.find(params[:id])
  end

  def update
    #@admin = Admin.find(params[:id])
    #params_admin = 

    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: 'Administrador atualizado com sucesso'
    else 
      render :edit
    end
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: 'Administrador excluído com sucesso'
    else 
      render :index
    end
  end
  
  private

  def params_admin
    params.require(:admin).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank? 
      params[:admin].extract!(:password, :password_confirmation)
    end
  end
end

app/controllers/admins_backoffice/archives_controller.rb
class AdminsBackoffice::ArchivesController < AdminsBackofficeController
    before_action :set_archive, only: %i[ show edit update destroy ]
  
    # GET /drops or /drops.json
    def index
      @archives = Archive.all.page(params[:page])
    end
  
    # GET /drops/1 or /drops/1.json
    def show
    end
  
    # GET /drops/new
    def new
      @archive = Archive.new
    end
  
    # GET /drops/1/edit
    def edit
    end
  
    # POST /drops or /drops.json
    def create
      @archive = Archive.new(archive_params)
  
      respond_to do |format|
        if @archive.save
          format.html { redirect_to admins_backoffice_archives_path(@archive), notice: "Arquivo carregado com sucesso." }
          format.json { render :show, status: :created, location: @archive }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @archive.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /drops/1 or /drops/1.json
    def update
      respond_to do |format|
        if @archive.update(archive_params)
          format.html { redirect_to admins_backoffice_archives_path(@archive), notice: "Arquivo atualizado com sucesso." }
          format.json { render :show, status: :ok, location: @archive }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @archive.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /drops/1 or /drops/1.json
    def destroy
      @archive.destroy
  
      respond_to do |format|
        format.html { redirect_to admins_backoffice_archives_path, notice: "Arquivo deletado com sucesso" }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_archive
        @archive = Archive.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def archive_params
        params.require(:archive).permit(:title, :description, :file)
      end
  end
  

app/controllers/admins_backoffice/members_controller.rb
class AdminsBackoffice::MembersController < AdminsBackofficeController
  before_action :set_member, only: %i[ show edit update destroy ]
  
  # GET /drops or /drops.json
  def index
    @members = Member.all.page(params[:page])
  end

  # GET /drops/1 or /drops/1.json
  def show
  end

  # GET /drops/new
  def new
    @member = Member.new
  end

  # GET /drops/1/edit
  def edit
  end

  # POST /drops or /drops.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to admins_backoffice_members_path(@member), notice: "Membro carregado com sucesso." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drops/1 or /drops/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to admins_backoffice_members_path(@member), notice: "Membro atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drops/1 or /drops/1.json
  def destroy
    @member.destroy

    respond_to do |format|
      format.html { redirect_to admins_backoffice_members_path, notice: "Membro deletado com sucesso" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:avatar, :first_name, :last_name, :email, :cell_phone, :birthdate, :address)
    end

    
      
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/archives_helper.rb
module AdminsBackoffice::ArchivesHelper
end

app/helpers/admins_backoffice/controls_helper.rb
module AdminsBackoffice::ControlsHelper
end

app/helpers/admins_backoffice/members_helper.rb
module AdminsBackoffice::MembersHelper
    # def avatar_url
    #     avatar = member.avatar
    #     avatar.attached? ? avatar : 'https://e7.pngegg.com/pngimages/84/165/png-clipart-united-states-avatar-organization-information-user-avatar-service-computer-wallpaper.png'
    # end
end

app/helpers/admins_backoffice/reports_helper.rb
module AdminsBackoffice::ReportsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
    def translate_attribute(object = nil, method = nil)
        if object && method
            object.model.human_attribute_name(method)
        else
            "Informe os parâmetros corretamente"
        end
    end
end

app/helpers/adminsbackoffice/members_helper.rb
module Adminsbackoffice::MembersHelper
end

app/views/admins_backoffice/archives/edit.html.erb
<%= render partial: 'admins_backoffice/archives/shared/form', locals:{action_message: 'Editando Arquivo'}%>

app/views/admins_backoffice/archives/index.html.erb
<h1><%=t('messages.listing', model: @archives.model_name.human(count:2))%></h1>


<div class="x_panel">
    <div class="x_title">
    <%# <h2>Hover rows <small>Try hovering over the rows</small></h2> %>
    
    <div class="clearfix"></div>
    </div>
    <div class="x_content">
    <table class="table table-hover">
        <thead>
      
            <%# <th> #</th> %>
            <th><%=translate_attribute(@archives, :title)%></th>
            <th><%=translate_attribute(@archives, :description)%></th>
            <th>
                <%=link_to new_admins_backoffice_archive_path, class:"btn btn-success btn-circle" do%>
                    <i class="fas fa-plus"></i>
                <%end%>
            </th>
        </tr>
        </thead>
        <tbody>
        <% @archives.each do |archive|%>
            <tr>
                <%# <td><%=archive.id%>
                <td><%=archive.title%></td>
                <td><%=archive.description%></td>
                <td style="width:120px">
                    <%=link_to admins_backoffice_archive_path(archive), class:"btn btn-primary btn-circle" do%>
                        <i class="fas fa-edit"></i>
                    <%end%>

                  
                    
                    <%=link_to admins_backoffice_archive_path(archive), method: :delete, 
                        class:"btn btn-danger btn-circle", 
                        data: {confirm:t('messages.confirm_with', item: archive.title)} do%>
                        <i class="fas fa-trash"></i>
                    <%end%>
                </td>
            </tr>
        <%end%>    
        </tbody>
    </table>
    
      <%= paginate @archives %>
    </div>
</div>

app/views/admins_backoffice/archives/new.html.erb
<%= render partial: 'admins_backoffice/archives/shared/form', locals:{action_message: 'Novo Arquivo'}%>

app/views/admins_backoffice/archives/show.html.erb
<h1>Arquivos</h1>


<div class="x_panel">
    <div class="x_title">
    <%# <h2>Hover rows <small>Try hovering over the rows</small></h2> %>
    
    <div class="clearfix"></div>
    </div>
    <div class="x_content">
    <table class="table table-hover">
        <thead>

        <thead>
        <tr>
            <th>#</th>
            <th>Título</th>
            <th>Descrição</th>
            <th>Arquivo</th>
        <tr>
        
        </thead>
        
        <tbody>
            <tr> 
                <th><%=@archive.id%></th>   
                <th><%=@archive.title%></th>
                <th><%= @archive.description %></th>
                <th><%= link_to 'Download', @archive.file%></th>
            </tr>
        </tbody>
       
    </table>
         <tr>
            <td style="width:120px">
                <%=link_to 'Voltar', admins_backoffice_archives_path, class:"btn btn-primary"%>
            </td>
        </tr>
    </div>
</div>