config/routes.rb
Rails.application.routes.draw do
  namespace :admins_backoffice do
    get 'members/index'
    
  end
  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index' # Dashboard
    resources :admins # Administradores
    resources :members # Cadastro de Membros
    resources :archives #arquivos
    root to: 'archives#index'
  end
  devise_for :users
  devise_for :admins
 
  get 'inicio', to: 'site/welcome#index'
  get 'admin', to: 'admins_backoffice/welcome#index'
  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # kaminari
  paginates_per 5       
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive.rb
class Archive < ApplicationRecord
    has_one_attached :file

     # kaminari
  paginates_per 5  
end

app/models/member.rb
class Member < ApplicationRecord
  has_one_attached :avatar
    
    # has_attached_file :avatar, styles: { medium: "50x50>", thumb: "25x25>" }
    # validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
    
    # kaminari
  paginates_per 5
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    layout :layout_by_resource

    protected

    def layout_by_resource
        if devise_controller? && resource_class == Admin
            "admin_devise"
        else
            "application"
        end
    end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    before_action :authenticate_user!
    layout 'users_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/members_helper.rb
module AdminsBackoffice::MembersHelper
    # def avatar_url
    #     avatar = member.avatar
    #     avatar.attached? ? avatar : 'https://e7.pngegg.com/pngimages/84/165/png-clipart-united-states-avatar-organization-information-user-avatar-service-computer-wallpaper.png'
    # end
end

app/helpers/admins_backoffice/reports_helper.rb
module AdminsBackoffice::ReportsHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
    def translate_attribute(object = nil, method = nil)
        if object && method
            object.model.human_attribute_name(method)
        else
            "Informe os parâmetros corretamente"
        end
    end
end

app/helpers/adminsbackoffice/members_helper.rb
module Adminsbackoffice::MembersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/admins_backoffice/admins/shared/_form.html.erb
<%# <h1>Editando</h1> %>


<div class="x_panel">
    <div class="x_title">
        <h1><%=action_message%></h1>
        
        <div class="clearfix"></div>
    </div>
    <%if @admin.errors.any?%>
        <div class="alert alert-danger alert-dismissible " role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
            </button>
            <ul>
               <% @admin.errors.full_messages.each do |message| %>
                 <li><%=message%></li>
               <%end%>
            </ul>
        </div>
    <%end%>
    <div class="x_content">

        <!-- start form for validation -->
        
        <%= form_with(model: [ :admins_backoffice, @admin ], local: true) do |form| %>
            <%=form.label :first_name%>
            <%=form.text_field :first_name, class:"form-control" %>

            <%=form.label :last_name%>
            <%=form.text_field :last_name, class:"form-control" %>
           
            <%=form.label :email%>
            <%=form.text_field :email, class:"form-control" %>
          
            <%=form.label :password%>
            <%=form.password_field :password, class:"form-control" %>
           
            <%=form.label :password_confirmation%>
            <%=form.password_field :password_confirmation, class:"form-control" %>
           
            <br>
            <button type='submit' class="btn btn-primary">Salvar</button>
            <%=link_to 'Voltar', admins_backoffice_admins_path, class:"btn btn-primary"%>

        <%end%>
        <!-- end form for validations -->

    </div>
</div>

app/views/layouts/admin_devise.html.erb
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Administrativo Junta Diaconal</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= stylesheet_link_tag    'admin_devise' %>
    
    <!-- Custom fonts for this template-->
    
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    

</head>

<body class="bg-gradient-success">

    <div class="container">
         <%= yield %>
        <!-- Outer Row -->
        

    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'admin_devise' %>
   

    <%if flash%>
        <% flash.each do |key, value| %>
            <script>
                $.bootstrapGrowl("<%=value%>", {
                    // ele: 'body', // which element to append to
                    type: 'danger', // (null, 'info', 'danger', 'success')
                    // offset: {from: 'top', amount: 20}, // 'top', or 'bottom'
                    align: 'right', // ('left', 'right', or 'center')
                    // width: 250, // (integer, or 'auto')
                    // delay: 4000, // Time while the message will be displayed. It's not equivalent to the *demo* timeOut!
                    allow_dismiss: true, // If true then will display a cross to close the popup.
                    stackup_spacing: 10 // spacing between consecutively stacked growls.
                });
            </script>
        <%end%>    
    <%end%>

    <%unless resource.errors.empty?%>
        <% resource.errors.full_messages.each do |msg| %>
            <script>
                $.bootstrapGrowl("<%=msg%>", {
                    // ele: 'body', // which element to append to
                    type: 'danger', // (null, 'info', 'danger', 'success')
                    // offset: {from: 'top', amount: 20}, // 'top', or 'bottom'
                    align: 'right', // ('left', 'right', or 'center')
                    // width: 250, // (integer, or 'auto')
                    // delay: 4000, // Time while the message will be displayed. It's not equivalent to the *demo* timeOut!
                    allow_dismiss: true, // If true then will display a cross to close the popup.
                    stackup_spacing: 10 // spacing between consecutively stacked growls.
                });
            </script>
        <%end%>    
    <%end%>
</body>

</html>

app/views/layouts/admins_backoffice.html.erb
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
       
    <title>Teste02</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= stylesheet_link_tag    'admins_backoffice' %>
    
    <!-- Custom fonts for this template-->
    <script src="https://kit.fontawesome.com/8eb9959284.js" crossorigin="anonymous"></script>
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-success sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
             
                <div class="sidebar-brand-text mx-3">
                    <%=link_to 'ADMINISTRATIVO JUNTA DIACONAL', admins_backoffice_welcome_index_path, class:"sidebar-brand d-flex align-items-center justify-content-center"%>
                </div>
           

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <%=link_to admins_backoffice_welcome_index_path, class:"nav-link" do%>
                    <i class="fas fa-home "></i>
                    <span>Início</span></a>
                <%end%>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <li class="nav-item">
                <%=link_to admins_backoffice_admins_path, class:"nav-link" do%>
                    <i class="fas fa-users fa-tachometer-alt"></i>
                    <span>Diáconos</span></a>
                <%end%>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <li class="nav-item">
                <%=link_to admins_backoffice_members_path, class:"nav-link" do%>
                    <i class="fas fa-user fa-tachometer-alt"></i>
                    <span>Membros</span></a>
                <%end%>
            </li>

             <!-- Divider -->
            <hr class="sidebar-divider">

            <li class="nav-item">
                <%=link_to admins_backoffice_archives_path, class:"nav-link" do%>
                    <i class=" fas fa-folder-open "></i>
                    <span>Arquivos</span></a>
                <%end%>
            </li>
  
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                       

                        <div class="topbar-divider d-none d-sm-block"></div>
                        
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                                    <%=current_admin.email%>
                                </span>
                                <%= image_tag'user.png',class:"img-profile rounded-circle"%>
                               
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                               
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <%=link_to destroy_admin_session_path, method: :delete do%>
                                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i> Logout
                                    <%end%>
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    
                    <%= yield %>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        
                         <span>Igreja Presbiteriana de Votorantim</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'admins_backoffice' %>

    <%if notice%>
        <script>
            $.bootstrapGrowl("<%=notice%>", {
                // ele: 'body', // which element to append to
                type: 'success', // (null, 'info', 'danger', 'success')
                // offset: {from: 'top', amount: 20}, // 'top', or 'bottom'
                align: 'right', // ('left', 'right', or 'center')
                // width: 250, // (integer, or 'auto')
                // delay: 4000, // Time while the message will be displayed. It's not equivalent to the *demo* timeOut!
                allow_dismiss: true, // If true then will display a cross to close the popup.
                stackup_spacing: 10 // spacing between consecutively stacked growls.
            });
        </script>
    <%end%>
    <script>
        $(function(){
            $('.datepicker').datepicker();
        });
    </script>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Administrativo Junta Diaconal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1>LAYOUT APPLICATION</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/site.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Administrativo Junta Diaconal</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= stylesheet_link_tag    'site' %>
    
    

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

     <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        

        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
          <% unless admin_signed_in?%>
            <li class="nav-item active">
              <%=link_to 'Entrar', new_admin_session_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%=link_to 'Cadastrar-se', new_admin_registration_path, class:"nav-link"%>
            </li> 
          <%else%>
            <li class="nav-item active">
              <%=link_to 'Administrativo', admins_backoffice_welcome_index_path, class:"nav-link"%>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%=current_admin.email%></a>
              <div class="dropdown-menu" aria-labelledby="dropdown01">
                <a class="dropdown-item">
                  <%=link_to  destroy_admin_session_path, method: :delete do%>
                     <i class="fa fa-sign-out fa-fw"></i> Sair
                  <%end%>
                </a>
                
                
              </div>
            </li> 
          <%end%>   
          </ul>
          
        </div>
      </nav>
      <br><br>
      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="text-center">
          
          <h1>Bem vindo a Junta Diaconal da Igreja<br>Presbiteriana de Votorantim</h1>
           
          
          <% unless admin_signed_in?%>
          
          
            <p>
              <%=link_to 'Entrar', new_admin_session_path, class:"btn btn-lg btn-success btn-block"%>
            </p><br>
            <h3>Ainda não se cadastrou?</h3>
            <p>
              <%=link_to 'Cadastre-se aqui', new_admin_registration_path, class:"btn btn-lg btn-secondary btn-block"%>
            </p><br> 
          <%else%>  
            <%=link_to admins_backoffice_welcome_index_path do %>
              <%=image_tag 'logo.png',style:"width:15em"%>
            <%end%>  
            <br><br>
            <p >Pois os que desempenharem bem o diaconato alcançam para si mesmos justa preeminência<br>e muita intrepidez na fé em Cristo Jesus. 1 Timóteo 3:13</p>
            <br>
            <p>
              <%=link_to 'Administrativo', admins_backoffice_welcome_index_path,  class:"btn btn-lg btn-success btn-block"%>
            </p>
            <p>
              <%=link_to 'Sair', destroy_admin_session_path, method: :delete,  class:"btn btn-lg btn-danger btn-block"%>
            </p>
          <%end%>  
         
        </div>    
      </div>

    </div> <!-- /container -->
    <footer class="text-center">
      Igreja Presbiteriana de Votorantim
    </footer>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'site' %>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <%if notice%>
        <script>
            $.bootstrapGrowl("<%=notice%>", {
                // ele: 'body', // which element to append to
                type: 'success', // (null, 'info', 'danger', 'success')
                // offset: {from: 'top', amount: 20}, // 'top', or 'bottom'
                align: 'right', // ('left', 'right', or 'center')
                // width: 250, // (integer, or 'auto')
                // delay: 4000, // Time while the message will be displayed. It's not equivalent to the *demo* timeOut!
                allow_dismiss: true, // If true then will display a cross to close the popup.
                stackup_spacing: 10 // spacing between consecutively stacked growls.
            });
        </script>
    <%end%>
  </body>
</html>